import { CLIENT_SCRIPTS } from "./client-scripts";

export function generateGlobalScript(): string {
  return /* js */ `// Autogenerated client scripts
 
htmx.on('form', 'htmx:xhr:progress', function(evt) {
  const field = htmx.find('#progress');
  field.style.display = "block";
  
  const value = evt.detail.loaded / evt.detail.total * 100;  
  if (value === 100) {
    htmx.find(field, 'span').innerText = "Processing files...";  
    htmx.find(field, 'progress').style.display="none";
  } else {
    htmx.find(field, 'span').innerText = "Uploading: " + value.toFixed(2) + "%";  
    htmx.find(field, 'progress').setAttribute('value', value);
  }
});

${Object.values(CLIENT_SCRIPTS)
  .map((value) => value.toFunctionStr())
  .join("\n")}`;
}
