nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmRegistryServer: "https://registry.npmjs.org"
npmPublishRegistry: "https://registry.npmjs.org"
npmAuthToken: "${NPM_AUTH_TOKEN}"
npmAlwaysAuth: true
npmPublishAccess: "public"

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"
