nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.12.0.cjs

catalog:
  "@typescript/native-preview": "7.0.0-dev.20251217.1"
  "@types/node": "^22.0.0"
  "@vitest/coverage-v8": "^4.0.0"
  oxfmt: "^0.18.0"
  oxlint: "^1.33.0"
  "oxlint-tsgolint": "^0.9.1"
  tsdown: "^0.18.1"
  vitest: "^4.0.0"
