nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_AUTH_TOKEN:-}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.12.0.cjs

catalog:
  "@typescript/native-preview": "^7.0.0-dev.20251213.1"
  "@types/node": "^22.0.0"
  "@vitest/coverage-v8": "^4.0.0"
  hono: "^4.11.0"
  oxlint: "^1.32.0"
  "oxlint-tsgolint": "^0.8.6"
  "prettier": "^3.7.4"
  tsdown: "^0.17.3"
  vitest: "^4.0.0"
  zod: "^4.1.0"
