// oxlint-disable sort-keys

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    { dirName: ".", type: "autogenerated" },
    {
      type: "category",
      label: "Tags",
      collapsed: false,
      items: [
        {
          href: "/docs/tags/hosting",
          label: "Hosting",
          type: "link",
        },
        {
          href: "/docs/tags/storage",
          label: "Storage",
          type: "link",
        },
        {
          href: "/docs/tags/database",
          label: "Database",
          type: "link",
        },
        {
          href: "/docs/tags/auth",
          label: "Auth",
          type: "link",
        },
        {
          href: "/docs/tags/ui",
          label: "UI",
          type: "link",
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
