name: Publish JSR (only)

on:
  workflow_dispatch:

jobs:
  publish-all:
    name: Publish all packages to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish to JSR
        run: npx -y turbo publish:jsr -- --sloppy-imports --token ${{ secrets.JSR_API_TOKEN }}
