name: Publish JSR (only)

on:
  workflow_dispatch:

jobs:
  publish-all:
    name: Publish all packages to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        packages:
          - "./packages/core"
          - "./packages/aws"
          - "./packages/azure"
          - "./packages/gcp"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install deps
        working-directory: ${{ matrix.packages }}
        run: deno install
      - name: Publish to JSR
        working-directory: ${{ matrix.packages }}
        run: deno publish --sloppy-imports --token ${{ secrets.JSR_API_TOKEN }}
