// oxlint-disable ban-types
// oxlint-disable sort-keys
// oxlint-disable no-new-func

class GlobalScript {
  name: string;
  args: string[];
  body: string;

  constructor(name: string, args: string[], body: string) {
    this.name = name;
    this.args = args;
    this.body = body;
  }

  toString(): string {
    return this.name;
  }

  toFunctionStr(): string {
    return `function ${this.name} (${this.args.join(",")}) {${this.body}}`;
  }
}

export const GLOBAL_SCRIPT = {
  toggleExpandedStoriesGroups: new GlobalScript(
    "toggleExpandedStoriesGroups",
    [],
    "alert('toggle')",
  ),
} satisfies Record<string, GlobalScript>;

export function globalScripts(): string {
  return /* js */ `// Autogenerated client scripts
 
htmx.on('form', 'htmx:xhr:progress', function(evt) {
  const field = htmx.find('#progress');
  field.style.display = "block";
  
  const value = evt.detail.loaded / evt.detail.total * 100;  
  if (value === 100) {
    htmx.find(field, 'span').innerText = "Processing files...";  
    htmx.find(field, 'progress').style.display="none";
  } else {
    htmx.find(field, 'span').innerText = "Uploading: " + value + "%";  
    htmx.find(field, 'progress').setAttribute('value', value);
  }
});

${Object.values(GLOBAL_SCRIPT)
  .map((value) => value.toFunctionStr())
  .join("\n")}`;
}
