// oxlint-disable ban-types
// oxlint-disable sort-keys
// oxlint-disable no-new-func

export const GLOBAL_SCRIPT = {
  toggleExpandedStoriesGroups: {
    name: "toggleExpandedStoriesGroups",
    args: [],
    body: "alert('toggle')",
    toString(): string {
      return this.name;
    },
  },
  // oxlint-disable-next-line no-unsafe-function-type
} satisfies Record<
  string,
  { name: string; args: unknown[]; body: string; toString: () => string }
>;

export function globalScripts(): string {
  return /* js */ `// Autogenerated client scripts
 
htmx.on('form', 'htmx:xhr:progress', function(evt) {
  const field = htmx.find('#progress');
  field.style.display = "block";
  
  const value = evt.detail.loaded / evt.detail.total * 100;  
  if (value === 100) {
    htmx.find(field, 'span').innerText = "Processing files...";  
    htmx.find(field, 'progress').style.display="none";
  } else {
    htmx.find(field, 'span').innerText = "Uploading: " + value + "%";  
    htmx.find(field, 'progress').setAttribute('value', value);
  }
});

${Object.values(GLOBAL_SCRIPT).map((value) => {
  return `function ${value.name} (${value.args.join(",")}) {${value.body}}\n`;
})}`;
}

new Function();
